
name: Hello world workflow
on:
  push:
  branch:
     -main
  pull_request:
      branches:
        -main
  workflow-dispatch:
jobs:
   hello:
     runs-on: ubuntu-latest
     steps:
       - uses: action/checkout@v2
       - name: hello world
         run: echo "Hello world"
         shell: bash
goodbye:
     runs-on: ubuntu-latest
     steps:
       - name: goodbye
         run: echo "goodbye"
         shell: bash 
