name: "Terraform"

on: 
  push: 
    branches: 
      - main
  pull_request: 

jobs: 
  terraform: 
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    env: 
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}    

    #use the bash shell whether the github acition runner is ubuntu-latest, windows-latest
    defaults: 
      run: 
        shell: bash
    steps: 
    - name: Checkout 
      uses: actions/checkout@v2
      
      # Terraform CLI token 
    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v1
      with: 
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} 

    # Terraform init   
    - name: Terraform init
      id: init
      run: terraform init
 
    # Terraform fmt
    - name: Terraform format          
      run: terraform fmt -check

      # Terraform plan
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'push'
      run: terraform plan  
      
      # Terraform Apply
    - name: Terraform Apply         
      if: github.ref == 'Yerolkar123/Repo-1' && github.event_name == 'push'
      run: terraform apply -auto-approve 
