name: "Terraform-plan-Infra-Release"

on: 
  push:
    paths:
      - '../'
    branches: 
      - main
  pull_request: 

jobs: 
  terraform-init: 
    name: "terraform-int"
    runs-on: ubuntu-latest
    environment: production
    env: 
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      ROOT_PATH: '/home/runner/work/Repo-1/Repo-1' 
    defaults: 
      run: 
        shell: bash
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with: 
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  
      # Terraform CLI token 
    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v1
      with: 
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         
    - name: Terraform init
      id: init
      run: terraform init 
      working-directory: ${{ env.ROOT_PATH }}

#   terraform-plan: 
#     needs: "terraform-init"
#     name: "terraform-plan"
#     runs-on: ubuntu-latest
#     environment: production

#     env: 
#       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
#       GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#       ROOT_PATH: '/home/runner/work/Repo-1/Repo-1' 

#     #use the bash shell whether the github acition runner is ubuntu-latest, windows-latest
#     defaults: 
#       run: 
#         shell: bash
#     steps: 
#     - name: Checkout
#       uses: actions/checkout@v2
#       with: 
#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
#       # Terraform CLI token 
#     - name: Setup Terraform 
#       uses: hashicorp/setup-terraform@v1
#       with: 
#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
         
#     - name: Terraform init
#       id: init
#       run: terraform init 
#       working-directory: ${{ env.ROOT_PATH }}

#     - name: Terraform Plan
#       id: plan
#       run: terraform plan
#       working-directory: ${{ env.ROOT_PATH }}
