name: 'Terraform'

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:

jobs:
  Terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production 
    steps: 
      name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  
      run: echo "terraform integrated" 
    

 
